### ISSUE TITLE
Enable dev release

### ISSUE THREAD

**Issue by beenje** [conda-forge/sardana-feedstock#1]
Hi @reszelaz and @cpascual!

At MAX IV, we'd like to have some dev release build (from the develop branch).

This is possible to do on conda-forge by creating a `dev` branch. See
https://conda-forge.org/docs/maintainer/knowledge_base.html#pre-release-builds

If that sounds ok to you, I'll create a "dev" branch and make a PR.

**Comment by cpascual** [comment]
Sounds good to me.

In fact, I was already considering investigating it for taurus too (now I'll be able to copy it from Sardana)

**Comment by beenje** [comment]
First dev release available.
Can be installed using: `conda create -n sardana -c conda-forge/label/sardana_dev -c conda-forge sardana`
